### ISSUE TITLE
Fix Learn to fly

### ISSUE THREAD

**Issue by Defualted** [SHSGames/shsgames.github.io#156]
I cannot play learn to fly #1 or #2 on mobile please fix… Thank you!

**Comment by Defualted** [comment]
Also fix it on computer the first game you just hover up very slowly please fix. and hurry! Thank you.

**Comment by MRPENGUINTHEFIRST1** [comment]
popcorn

**Comment by JoshMerlino** [comment]
Compatibility on mobile is not officially supported by Ruffle to my knowledge.
This is a duplicate of #180
