### ISSUE TITLE
Dark mode/ Light mode bug

### ISSUE THREAD

**Issue by TheGuy888** [SHSGames/shsgames.github.io#157]
If you hold down any key on your keyboard, and spam click the dark mode/light mode button, intense flashing ensues for an uncomfortable amount of time... (Although it may take a few seconds between flashes.) 
So, either:
1. fix it
or
2. put some kind of popup saying: don't do that* ^^^

*if you have epilepsy

**Comment by JoshMerlino** [comment]
Thanks for bringing this to my attention. The hotkey for the theme switcher `F10` was interfering with gameplay keyboard optimization.

Should be good to go.
