### ISSUE TITLE
Madness Project Nexus Issue 

### ISSUE THREAD

**Issue by OOF-LORD** [SHSGames/shsgames.github.io#161]
The arena combat mode is freezing when I hit new game.

**Comment by JoshMerlino** [comment]
I just added this game last night, and while I was testing, I noticed it took a while to load in the emulator, even for me. I have a RTX 3060 and a Ryzen 5900HX, It could just be a hefty game that ruffle needs a while to convert to web assembly, especially on lower end devices like Chromebooks or other school computers. Try leaving it open for a few minutes to let it load before you try to play.

If that doesn't work, please reopen this issue.

**Comment by OOF-LORD** [comment]
Its not loading I have been waiting for 30min
and no luck

**Comment by OOF-LORD** [comment]
Duplicate of # Madness Project Nexus Issue
