### ISSUE TITLE
Learn to fly & learn to fly 2 is broken

### ISSUE THREAD

**Issue by MRPENGUINTHEFIRST1** [SHSGames/shsgames.github.io#180]
In learn to Fly 1&2 the puppet will only go up slowly and you can't launch. And, Learn to fly 1 is just Learn to fly 2 and has the same issue . Please Fix!!!

**Comment by JoshMerlino** [comment]
This appears to be a problem with ruffle-rs/ruffle. Unfortunately all I can do is display a warning.

**Comment by JoshMerlino** [comment]
And for reference: The problems I'm running into are physics aren't implemented correctly.

**Comment by Woahcheeto** [comment]
@JoshMerlino is that possible to fix?

**Comment by JoshMerlino** [comment]
Duplicate of #350. Please seek support within that issue.
