### ISSUE TITLE
Electricman 2

### ISSUE THREAD

**Issue by hellowpplz** [SHSGames/shsgames.github.io#185]
When you start up electroman 2, you go through the first part of the tutorial telling you to use asd and you have to beat that little AI. Then after that, it automatically skippes the text, and normally the bots that you fight after that text are stuck running into the walls on the menu screen. You try to select a level, any level, and it counts down, and then this shows up, 
![Screenshot 2021-11-19 5 44 28 PM](https://user-images.githubusercontent.com/94722448/142700799-20e0c599-fe1a-4eff-83e7-76cbcf755fef.png)

**Comment by hellowpplz** [comment]
And I already reported it to the ruffle github page, yes.

**Comment by JoshMerlino** [comment]
Issue appears to be fixed

**Comment by hellowpplz** [comment]
I just tried it and they still appear. However, this time it doesn't crash. Instead it won't let me select any of the levels. This time I tried saving and the restarting it but I still cant select any levels. I am pretty sure I am updated too. I am using Ruffle (nightly 2021-12-02)
