### ISSUE TITLE
Fleeing the complex

### ISSUE THREAD

**Issue by 1333481** [SHSGames/shsgames.github.io#197]
Hello I am trying to add freeing the complex to my mirror of SHSGames but the file is larger than 20mb and jsDelivr doesnt support files that large. Can I just use the github link for the .swf. I uploaded the .swf to github.

**Comment by JoshMerlino** [comment]
Unfortunately no, The reason I use JSDelivr is because GitHub enforces (CORS) which essentially blocks other sites from accessing content on their site without authorization. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by JoshMerlino** [comment]
If you found another CDN that will host the file, you can add it through that link.
