### ISSUE TITLE
CubeField has lines connecting from block to block and to the player, making the game look scuffed and making it laggy.

### ISSUE THREAD

**Issue by BrumSickle** [SHSGames/shsgames.github.io#203]
https://shsgames.github.io/g/6a905bb2/cubefield

Lines connecting from block to block and to the player.
Lines shouldn't be there.

![image](https://user-images.githubusercontent.com/95693721/145034554-9e4fa200-6100-493c-b955-57bc16b02a95.png)

**Comment by JoshMerlino** [comment]
Hopefully this gets fixed when I update Ruffle in the near future... I try to update Ruffle whenever there's a new version out which is every day or so.
