### ISSUE TITLE
[Cookie Clicker] - [Crashed]

### ISSUE THREAD

**Issue by Anthony6494303** [SHSGames/shsgames.github.io#207]
**URL**: Paste the url that the problem is on here.
**Version**: Paste the version number from the bottom of the page. e.g. *a.b.c-xyz*.

**Observed Behavior**: Explain what's wrong.

**Expected Behavior**: Explain what should happen.

**How to Reproduce**: If the problem occurs after a complicated list of actions, explain each step here, otherwise delete this section.

**Include screenshots if possible**

**Comment by JoshMerlino** [comment]
No information provided
