### ISSUE TITLE
ELECTRIC MAN 2- Glitched out

### ISSUE THREAD

**Issue by SyrusPlayz** [SHSGames/shsgames.github.io#226]
https://shsgames.github.io/g/6f2e0289/electric-man-2
v6.0.30-0

After first level of tutorial, it glitched out and the holograms were still there while it was on the selection screen, and when I clicked the first level, they started attacking before the match started, then it crashed.

You should be able to go onto a 2nd level of the tutorial and defeat the holograms, then get sent to the selection screen

![image](https://user-images.githubusercontent.com/96263723/146444708-86e85d37-9717-483b-a361-b925f895afb4.png)

**Comment by JoshMerlino** [comment]
fixed in 009d8d8
