### ISSUE TITLE
slope has an issue

### ISSUE THREAD

**Issue by moxiepeterson** [SHSGames/shsgames.github.io#272]
**URL**: Paste the url that the problem is on here.
**Version**: Paste the version number from the bottom of the page. e.g. *a.b.c-xyz*.

**Observed Behavior**: Explain what's wrong.

**Expected Behavior**: Explain what should happen.

**How to Reproduce**: If the problem occurs after a complicated list of actions, explain each step here, otherwise delete this section.

**Include screenshots if possible**

https://shsgames.github.io/g/c42ef5ef/slope
The ball in slope, kind of jumps for random reasons, you can be going down a straight path, and it will bump you up.

**Comment by JoshMerlino** [comment]
This is an issue with the compiled game from Y8.

**Comment by moxiepeterson** [comment]
are you able to fix it??

**Comment by moxiepeterson** [comment]
it ruins the entire game
