### ISSUE TITLE
Error Message on opening run 3

### ISSUE THREAD

**Issue by PotatoSnail64** [SHSGames/shsgames.github.io#291]
https://sh.9pfs.repl.co/g/1a9da8ca/run-3

v9.0.11-33

When opening run 3 it gives you a message that says that flash player is no longer supported on browsers in 2021, and that the game will not work as intended. When you click run anyway, it gives you a black screen. Run 3 should be playable without a flash player installed.

![image](https://user-images.githubusercontent.com/92490843/151172508-0b0a7bae-3078-4dea-8076-3928f37c6e70.png)

**Comment by hello-smile6** [comment]
> https://sh.9pfs.repl.co/g/1a9da8ca/run-3
> 
> v9.0.11-33
> 
> When opening run 3 it gives you a message that says that flash player is no longer supported on browsers in 2021, and that the game will not work as intended. When you click run anyway, it gives you a black screen. Run 3 should be playable without a flash player installed.
> 
> ![image](https://user-images.githubusercontent.com/92490843/151172508-0b0a7bae-3078-4dea-8076-3928f37c6e70.png)

That means that it isn't going to work. If you want to make it work, feel free.
https://ruffle.rs/

**Comment by JoshMerlino** [comment]
Run 3 is a flash game. At this time it is not fully supported in ruffle...
