### ISSUE TITLE
dad n me

### ISSUE THREAD

**Issue by yourboybraybray** [SHSGames/shsgames.github.io#325]
**URL**: Paste the url that the problem is on here.
**Version**: Paste the version number from the bottom of the page. e.g. *a.b.c-xyz*.

**Observed Behavior**: Explain what's wrong.

**Expected Behavior**: Explain what should happen.

**How to Reproduce**: If the problem occurs after a complicated list of actions, explain each step here, otherwise delete this section.

**Include screenshots if possible**

**Comment by hello-smile6** [comment]
@JoshMerlino Think this is spam, just letting you know in case this notification gets buried

**Comment by JoshMerlino** [comment]
No information provided
