### ISSUE TITLE
Mario Kart doesnt work

### ISSUE THREAD

**Issue by pixsplanet** [SHSGames/shsgames.github.io#372]
**URL**: Paste the url that the problem is on here.
https://sh.9pfs.repl.co/g/1b2da2a6/mario-kart

**Version**: Paste the version number from the bottom of the page. e.g. *a.b.c-xyz*.
v15.2.1

**Observed Behavior**: Explain what's wrong.
It just full on doesn't work

**Expected Behavior**: Explain what should happen.
I should be able to play

**Include screenshots if possible**
![image](https://user-images.githubusercontent.com/76448871/160684361-65565acc-4ff5-434b-bd40-26749aee5abe.png)

**Comment by JoshMerlino** [comment]
I fixed this a few days ago. You might have to clear your cache. If that dosnt work, clear all website storage through the devtools (`CTRL`+`SHIFT`+`I`)

![image](https://user-images.githubusercontent.com/31785395/166295698-42269f84-e838-410a-af79-34834e095c38.png)
