### ISSUE TITLE
Just a bit of a rant

### ISSUE THREAD

**Issue by Lhinger** [SHSGames/shsgames.github.io#399]
I love the site but some popular kid at my school found out and being the retards they are, its gonna spread like wildfire and be blocked by the end of the week.

**Comment by JoshMerlino** [comment]
It happens, there are tons of links in the readme that should be good alternatives mirrors incase it gets blocked.

Also in the future, Use the discussions tab for non-issues. Just helps me stay organized

**Comment by hello-smile6** [comment]
> It happens, there are tons of links in the readme that should be good alternatives mirrors incase it gets blocked.
> 
> Also in the future, Use the discussions tab for non-issues. Just helps me stay organized

If you want a mirror that will never be blocked, use [OpenNIC](https://opennic.org/) and [shs.libre](http://shs.libre/).
