### ISSUE TITLE
Extremely laggy

### ISSUE THREAD

**Issue by Lhinger** [SHSGames/shsgames.github.io#409]
**URL**: (https://shsg.herokuapp.com/g/1a6ec2bc/madness-project-nexus)
**Version**: v17.4.1

**Observed Behavior**: the game is running at less then 10 fps for seemingly no reason, my computer is not great but it should definitely be able to run this at atleast 20-27 fps

**Expected Behavior**: It should run at around 60+ fps

**Include screenshots if possible**
![Screenshot 2022-04-22 11 48 14 AM](https://user-images.githubusercontent.com/93882461/164776121-31e2d9c9-3a54-49ca-aa98-7ce3023bf1d9.png)

**Comment by JoshMerlino** [comment]
Runs at 143/110 for me, although I'm running a RTX3060 and 144hz monitors.
