### ISSUE TITLE
Cookie Clicker

### ISSUE THREAD

**Issue by Username12300000** [SHSGames/shsgames.github.io#462]
**URL**: https://shsgames.github.io/g/599cbfd1/cookie-clicker
**Version**: Paste the version number from the bottom of the page. e.g. *a.b.c-xyz*.

**Observed Behavior**: Game is broken

**Expected Behavior**: Should work.

**How to Reproduce**: If the problem occurs after a complicated list of actions, explain each step here, otherwise delete this section.

**Include screenshots if possible**
![image](https://user-images.githubusercontent.com/105867974/169312176-d1d707a4-7686-4804-98f6-dcf6478d1bbe.png)
![Screenshot 2022-05-19 100255](https://user-images.githubusercontent.com/105867974/169312283-95fb82be-abc7-45e5-a72e-a124f2b1dab3.jpg)

**Comment by JoshMerlino** [comment]
please clear your browser cache and try again
